name: gh-pages
on:
  push:
    branches:
      - main
      - develop

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.status.outputs.value }}
    steps:
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - id: status
        # using a run statement for each command does not work
        run: |
          OUT=`node .github/script/check-for-changes-within-24h.mjs "src"`
          echo "$OUT check-for-changes step"
          echo "::set-output name=value::$OUT"
  setup-gh-pages-files:
    needs: check-for-changes
    runs-on: ubuntu-latest
    if: ${{ needs.check-for-changes.outputs.output == 'run' }}
    steps:
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: node .github/script/setup-test.mjs
      - run: ls dist
      - run: echo running on branch ${{ env.BRANCH }}
      - run: npm run doc ${{ env.BRANCH }}
      - run: npm run coverage ${{ env.BRANCH }}
      - run: ls gh-pages/${{ env.BRANCH }}
      - uses: actions/upload-artifact@v3
        with:
          name: gh-pages-artifacts
          path: gh-pages/*
  update-coveralls:
    needs: setup-gh-pages-files
    runs-on: ubuntu-latest
    steps:
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/download-artifact@v4
        with:
          name: gh-pages-artifacts
          path: gh-pages
      - run: ls
      - run: ls gh-pages
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: gh-pages/${{ env.BRANCH }}/coverage/lcov.info
  update-gh-pages:
    needs: setup-gh-pages-files
    runs-on: ubuntu-latest
    steps:
      - run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}
      - uses: actions/download-artifact@v4
        with:
          name: gh-pages-artifacts
          path: gh-pages
      - run: ls
      - run: ls gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
